language:
  - swift
osx_image: xcode12.2
script:
  - xcodebuild -scheme UserAgency -sdk iphonesimulator -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
