language: swift
os: osx
branches:
  only:
  - main
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
jobs:
  include:
  - stage: "Builds"
    script: xcodebuild -scheme UserAgency SWIFT_VERSION=5.3 clean build
    osx_image: xcode12
    name: "Swift 5.3"
    after_success: bash <(curl -s https://codecov.io/bash)
